col TSNAME format a30
col FILESIZE_DISPLAY format a15
SELECT BTYPE, FILE#, INCREMENTAL_LEVEL, CHECKPOINT_TIME, MARKED_CORRUPT, COMPRESSION_RATIO, TS#, TSNAME, FILESIZE_DISPLAY
FROM V$BACKUP_DATAFILE_DETAILS
WHERE ID1 = &SET_STAMP
order by FILESIZE asc;