-- identificar scn anterior
SELECT V$TRANSACTION.SES_ADDR, V$TRANSACTION.START_SCNB, V$SESSION.USERNAME, V$SESSION.MACHINE
FROM V$TRANSACTION
	INNER JOIN V$SESSION
		ON V$TRANSACTION.SADDR = V$SESSION.SADDR
WHERE START_SCNB < 
	    (SELECT START_SCNB
	    FROM V$SQLAREA
		 INNER JOIN V$SESSION
			ON V$SQLAREA.ADDRESS = V$SESSION.SQL_ADDRESS    
		 INNER JOIN V$TRANSACTION
			ON V$TRANSACTION.SADDR = V$SESSION.SADDR
	    WHERE 
        	AND V$SQLAREA.SQL_TEXT LIKE 'alter tablespace%')
ORDER BY START_SCNB;


