prompt *** gerar sinonimos para todos os objetos do schema de origem no schema de destino **
prompt 
def SCHEMADESTINO = &SCHEMADESTINO
def SCHEMAORIGEM = &SCHEMAORIGEM

SELECT 'CREATE SYNONYM ' || '&SCHEMADESTINO' || '.' || OBJECT_NAME || ' FOR ' || '&SCHEMAORIGEM' || '.' || OBJECT_NAME || '; '
FROM DBA_OBJECTS
WHERE OWNER = UPPER('&SCHEMAORIGEM')
AND OBJECT_TYPE IN ('SEQUENCE','PROCEDURE','PACKAGE','TABLE','FUNCTION', 'SYNONYM', 'MATERIALIZED VIEW', 'TYPE', 'VIEW')
ORDER BY OBJECT_TYPE;

undef SCHEMADESTINO
undef SCHEMAORIGEM
