select *
from
(SELECT * FROM CRM_LOGS_DE_PROCESSAMENTO L
WHERE L.DATA_DO_PROCESSAMENTO >= TRUNC(SYSDATE-1)
AND L.IDENTIFICADOR_DO_SISTEMA LIKE  '%CUBOITEM%'
AND L.HORA_DA_EXECUCAO >= TRUNC(SYSDATE-1)
AND L.CODIGO_DA_FILIAL IN (1008)
--AND L.DATA_DO_PROCESSAMENTO >= to_date('28/10/2014 14:00:00', 'DD/MM/YYYY HH24:MI:SS')
order by SEQUENCIA_DO_LOG desc)
where rownum < 15
order by SEQUENCIA_DO_LOG asc
/
