col username for a30
col CCLASS_NAME for a30
col PROGRAM  for a30
col MACHINE  for a30
col CONNECTION_STATUS for a20
col PURITY for a10

PROMPT ##### TODAS SESSOES ########
select USERNAME, PURITY, PROCESS_ID, PROGRAM, MACHINE, CONNECTION_STATUS, CCLASS_NAME 
from V$CPOOL_CONN_INFO
order by CCLASS_NAME;

PROMPT 
PROMPT 
PROMPT ##### TOTAIS POR USER #########
select USERNAME, CCLASS_NAME , COUNT(1) CTD
from V$CPOOL_CONN_INFO
group by CCLASS_NAME , USERNAME
order by CCLASS_NAME , USERNAME;

PROMPT 
PROMPT 
PROMPT ##### TOTAIS POR MACHINE #########
select MACHINE, CCLASS_NAME , COUNT(1) CTD
from V$CPOOL_CONN_INFO
GROUP BY CCLASS_NAME, MACHINE 
order by CCLASS_NAME, MACHINE;
