
	col POOL_NAME for a30

	PROMPT ######### TOTAIS ##############
	select POOL_NAME, HISTORIC_MAX, NUM_OPEN_SERVERS, NUM_BUSY_SERVERS, NUM_AUTH_SERVERS, CLIENT_REQ_TIMEOUTS, NUM_AUTHENTICATIONS, NUM_PURGED FROM V$CPOOL_STATS;

	PROMPT ######### RATIOS ##############
	select POOL_NAME, 
		round(NUM_HITS / NUM_REQUESTS * 100, 2) HITS_RATIO,
		round(NUM_MISSES / NUM_REQUESTS * 100, 2) MISSES_RATIO,
	        round(NUM_WAITS / NUM_REQUESTS * 100, 2) WAITS_RATIO, 
	        NUM_REQUESTS, NUM_HITS, NUM_MISSES, NUM_WAITS
	 from V$CPOOL_STATS;
