prompt *** gerar os grants para sinonimos, conforme tipos do schema origem**
prompt 
def SCHEMA_DESTINO = &SCHEMA_DESTINO
def SCHEMA_ORIGEM = &SCHEMA_ORIGEM

SELECT 'GRANT ' || CASE 
						WHEN OBJECT_TYPE IN ('TABLE') 
							THEN 'SELECT, INSERT, UPDATE, DELETE'
						WHEN OBJECT_TYPE IN ('SEQUENCE') 
							THEN 'SELECT'
						WHEN OBJECT_TYPE IN ('PROCEDURE','PACKAGE','FUNCTION')
							THEN 'EXECUTE'
						ELSE 'ERRO'
				   END || ' ON ' || UPPER('&SCHEMA_ORIGEM') || '.' || OBJECT_NAME || ' TO ' || UPPER('&SCHEMA_DESTINO') || ';'
FROM DBA_OBJECTS O
	 INNER JOIN DBA_SYNONYMS S
		ON S.TABLE_OWNER = O.OWNER
		AND S.TABLE_NAME = O.OBJECT_NAME
WHERE O.OWNER = UPPER('&SCHEMA_ORIGEM')
   AND O.OBJECT_TYPE IN ('TABLE','SEQUENCE','PROCEDURE','PACKAGE','FUNCTION', 'TYPE', 'MATERIALIZED VIEW', 'VIEW')
  AND S.OWNER = UPPER('&SCHEMA_DESTINO')  
ORDER BY S.TABLE_NAME;

undef SCHEMA_DESTINO
undef SCHEMA_ORIGEM