prompt *** gerar os grants para todos objetos do schema, conforme tipos do schema origem**
prompt 
def SCHEMA_DESTINO = &SCHEMA_DESTINO
def SCHEMA_ORIGEM = &SCHEMA_ORIGEM

SELECT 'GRANT ' || CASE 
						WHEN OBJECT_TYPE IN ('TABLE') 
							THEN 'SELECT, INSERT, UPDATE, DELETE'
						WHEN OBJECT_TYPE IN ('SEQUENCE') 
							THEN 'SELECT'
						WHEN OBJECT_TYPE IN ('PROCEDURE','PACKAGE','FUNCTION')
							THEN 'EXECUTE'
						ELSE 'ERRO'
				   END || ' ON ' || UPPER('&SCHEMA_ORIGEM') || '.' || OBJECT_NAME || ' TO ' || UPPER('&SCHEMA_DESTINO') || ';'
FROM DBA_OBJECTS O
WHERE O.OWNER = UPPER('&SCHEMA_ORIGEM')
   AND O.OBJECT_TYPE IN ('TABLE','SEQUENCE','PROCEDURE','PACKAGE','FUNCTION')  
ORDER BY O.OBJECT_TYPE, O.OBJECT_NAME;

undef SCHEMA_DESTINO
undef SCHEMA_ORIGEM