col OWNER for a30
col MVIEW_NAME for a30
col MASTER_LINK for a30
col REFRESH_MODE for a30
col REFRESH_METHOD for a30

SELECT OWNER, MVIEW_NAME, MASTER_LINK, UPDATABLE, REFRESH_MODE, REFRESH_METHOD, LAST_REFRESH_DATE, LAST_REFRESH_END_TIME, STALE_SINCE
FROM DBA_MVIEWS
WHERE OWNER LIKE UPPER('&OWNER')
	  AND MVIEW_NAME LIKE UPPER('&MVIEW_NAME');