SELECT DECODE(DF.FILE_ID, TBS.MIN_file_id, 'CREATE', 'ALTER') || ' TABLESPACE ' || TBS.tablespace_name || 
	   DECODE(DF.FILE_ID, TBS.MIN_file_id, '', ' ADD') || ' datafile ''' ||  DF.FILE_NAME || ''' SIZE ' || TO_CHAR(ROUND(DF.BYTES / 1024, 0)) || 'K' ||
	   ' AUTOEXTEND ' || DECODE(DF.AUTOEXTENSIBLE, 'YES', 'ON NEXT ' || ROUND(INCREMENT_BY * BLOCK_SIZE / 1024,0) || 'K', 'OFF')   ||
	   ' MAXSIZE ' || DECODE(MAXBYTES, 0, 'UNLIMITED;', TO_CHAR(ROUND(MAXBYTES  / 1024, 0)) || 'K;')
FROM (  select PAR.tablespace_name, MIN(DF.file_id) MIN_file_id, MIN(TS.BLOCK_SIZE) AS BLOCK_SIZE
		from dba_tab_partitions PAR
			 INNER JOIN DBA_DATA_FILES DF 
				ON PAR.TABLESPACE_NAME = DF.TABLESPACE_NAME
			 INNER JOIN DBA_TABLESPACES TS
				ON TS.TABLESPACE_NAME = DF.TABLESPACE_NAME
		where PAR.table_owner = 'BRIDGE_ACCT'
		group by PAR.tablespace_name
		union
		select SEG.tablespace_name, MIN(DF.file_id) MIN_file_id, MIN(TS.BLOCK_SIZE) AS BLOCK_SIZE
		from dba_segments SEG
			 INNER JOIN DBA_DATA_FILES DF 
				ON SEG.TABLESPACE_NAME = DF.TABLESPACE_NAME
			 INNER JOIN DBA_TABLESPACES TS
				ON TS.TABLESPACE_NAME = DF.TABLESPACE_NAME
		where SEG.owner  = '&OWNER'
		group by SEG.tablespace_name) TBS
	INNER JOIN DBA_DATA_FILES DF 
		ON TBS.TABLESPACE_NAME = DF.TABLESPACE_NAME		
ORDER BY TBS.TABLESPACE_NAME, DF.FILE_ID