set verify off
set echo off
set long 999999
col SERVICE format a10
col MODULE format a10
col FIRST_LOAD_TIME format a20
col LAST_LOAD_TIME format a20
define PLAN_HASH_VALUE=&PLAN_HASH_VALUE
prompt "VALOR ACUMULADO:"
	SELECT sum(SHARABLE_MEM + PERSISTENT_MEM + RUNTIME_MEM) AS SUM_MEM, sum(EXECUTIONS) as EXECUTIONS, sum(BUFFER_GETS) as BUFFER_GETS,
		   round(sum(CPU_TIME) / 1000) as CPU_TIME_MS, round(sum(ELAPSED_TIME) / 1000) as ELAPSED_TIME, sum(DISK_READS) as DISK_READS, 
		   sum(ROWS_PROCESSED) as ROWS_PROCESSED,  sum(DIRECT_WRITES) as DIRECT_WRITES, sum(FETCHES) as FETCHES, 
		   sum(USERS_EXECUTING) as USERS_EXECUTING
	FROM V$SQL
	WHERE PLAN_HASH_VALUE='&PLAN_HASH_VALUE';
prompt 
	SELECT round(sum(APPLICATION_WAIT_TIME) / 1000) APPLICATION_WAIT_TIME_MS, 
			round(sum(CONCURRENCY_WAIT_TIME) / 1000) CONCURRENCY_WAIT_TIME_MS,
			round(sum(CLUSTER_WAIT_TIME) / 1000) CLUSTER_WAIT_TIME_MS,
			round(sum(USER_IO_WAIT_TIME) / 1000) USER_IO_WAIT_TIME_MS,
			round(sum(PLSQL_EXEC_TIME) / 1000) PLSQL_EXEC_TIME_MS,
			round(sum(JAVA_EXEC_TIME) / 1000) JAVA_EXEC_TIME_MS,
			OPTIMIZER_MODE 
	FROM V$SQL
	WHERE PLAN_HASH_VALUE='&PLAN_HASH_VALUE'
	group by OPTIMIZER_MODE;
prompt 
prompt 
prompt "VALOR POR EXECUCAO:"
	SELECT 
		round(SUM(SHARABLE_MEM + PERSISTENT_MEM + RUNTIME_MEM) / SUM(DECODE(EXECUTIONS, 0, 1, EXECUTIONS))) AS SUM_MEM, 
		ROUND(SUM(BUFFER_GETS)            / SUM(DECODE(EXECUTIONS, 0, 1, EXECUTIONS))) AS AVG_BUFFER_GETS, 
		ROUND((SUM(CPU_TIME)     / 1000)  / SUM(DECODE(EXECUTIONS, 0, 1, EXECUTIONS)))  AS AVG_CPU_MS,
		ROUND((SUM(ELAPSED_TIME) / 1000)  / SUM(DECODE(EXECUTIONS, 0, 1, EXECUTIONS)))   AS AVG_ELAPSED_MS,
		ROUND(SUM(DISK_READS)             / SUM(DECODE(EXECUTIONS, 0, 1, EXECUTIONS))) AS AVG_DISK_READS,
		ROUND(SUM(ROWS_PROCESSED)         / SUM(DECODE(EXECUTIONS, 0, 1, EXECUTIONS))) AS AVG_ROWS,
		ROUND(SUM(DIRECT_WRITES)          / SUM(DECODE(EXECUTIONS, 0, 1, EXECUTIONS))) AS AVG_DIRECT_WRITES,
		ROUND(SUM(FETCHES)                / SUM(DECODE(EXECUTIONS, 0, 1, EXECUTIONS))) AS AVG_FETCHES
	FROM V$SQL
	WHERE PLAN_HASH_VALUE='&PLAN_HASH_VALUE';
	
prompt "WAIT TIME POR EXECUCAO EM MILISEGUNDOS"
	SELECT ROUND((SUM(APPLICATION_WAIT_TIME) / 1000) / SUM(DECODE(EXECUTIONS, 0, 1, EXECUTIONS))) AS AVG_APPLICATION_TIME_MS, 
	   	   ROUND((SUM(CONCURRENCY_WAIT_TIME) / 1000) / SUM(DECODE(EXECUTIONS, 0, 1, EXECUTIONS))) AS AVG_CONCURRENCY_TIME_MS, 
		   ROUND((SUM(USER_IO_WAIT_TIME)     / 1000) / SUM(DECODE(EXECUTIONS, 0, 1, EXECUTIONS))) AS AVG_IO_TIME_MS, 
		   ROUND((SUM(PLSQL_EXEC_TIME)       / 1000) / SUM(DECODE(EXECUTIONS, 0, 1, EXECUTIONS))) AS AVG_PLSQL_TIME_MS, 
		   ROUND((SUM(JAVA_EXEC_TIME)        / 1000) / SUM(DECODE(EXECUTIONS, 0, 1, EXECUTIONS))) AS AVG_JAVA_TIME_MS,
		   ROUND((SUM(CLUSTER_WAIT_TIME)     / 1000) / SUM(DECODE(EXECUTIONS, 0, 1, EXECUTIONS))) AS AVG_CLUSTER_TIME_MS 
	FROM V$SQL
	WHERE PLAN_HASH_VALUE='&PLAN_HASH_VALUE';
prompt 
prompt "GERAL DO SQL:"                         
	SELECT sql_id, PARSING_SCHEMA_NAME, 
		ROUND(SUM(BUFFER_GETS) / SUM(DECODE(EXECUTIONS, 0, 1, EXECUTIONS))) AS AVG_BUFFER_GETS, 
		ROUND((SUM(CPU_TIME)     / 1000)  / SUM(DECODE(EXECUTIONS, 0, 1, EXECUTIONS)))  AS AVG_CPU_MS,
		ROUND((SUM(ELAPSED_TIME) / 1000)  / SUM(DECODE(EXECUTIONS, 0, 1, EXECUTIONS)))   AS AVG_ELAPSED_MS,
		ROUND(SUM(DISK_READS)             / SUM(DECODE(EXECUTIONS, 0, 1, EXECUTIONS))) AS AVG_DISK_READS, 
		SUM(EXECUTIONS) as EXECUTIONS,
		sum(USERS_EXECUTING) as USERS_EXECUTING
	FROM V$SQL
	WHERE PLAN_HASH_VALUE='&PLAN_HASH_VALUE'
	group by sql_id, PARSING_SCHEMA_NAME
	order by AVG_BUFFER_GETS;
prompt 
prompt 
UNDEF PLAN_HASH_VALUE
set verify on