accept LOG_ID number DEFAULT '0' PROMPT 'LOG_ID OU TODOS 0 ? : '
accept JOB_NAME CHAR default '%' PROMPT 'LIKE JOB_NAME(DEF %): '

BREAK ON JOB_NAME SKIP 1

COL ERRORS FOR a100 WRAPPED	
COL OUTPUT FOR a100 WRAPPED
COL STATUS FOR a20
col JOB_NAME for a30
col LOG_DATE for a32
col REQ_START_DATE for a32
col ACTUAL_START_DATE for a32
col RUN_DURATION for a20
col SESSION_ID for a20
col CPU_USED for a20

SELECT JOB_NAME, 
	LOG_DATE
	,STATUS
	,ERROR#
	,REQ_START_DATE
	,ACTUAL_START_DATE
	,RUN_DURATION
	,INSTANCE_ID
	,SESSION_ID
	,CPU_USED
	,ERRORS
	,OUTPUT
FROM dba_scheduler_job_run_details
WHERE (LOG_ID = &LOG_ID OR &LOG_ID = 0)
  AND UPPER(JOB_NAME) LIKE UPPER('&JOB_NAME');

undef LOG_ID
undef JOB_NAME