BREAK ON JOB_NAME SKIP 1
accept JOB_NAME CHAR default '%' PROMPT 'LIKE JOB_NAME(DEF %): '
col OWNER for a20
col JOB_NAME for a30
col USER_NAME for a30
col OPERATION for a30
col STATUS for a30
col LOG_DATE for a32
col LOG_ID for 999999999

SELECT * 
FROM (SELECT 
	JOB_NAME
	,LOG_ID
	,LOG_DATE
	,OWNER
	,OPERATION
	,STATUS
	,USER_NAME
	FROM DBA_SCHEDULER_JOB_LOG
	WHERE UPPER(JOB_NAME) LIKE UPPER('&JOB_NAME')
	ORDER BY LOG_DATE DESC) TBL
WHERE ROWNUM <= 10
ORDER BY LOG_DATE DESC;
undef JOB_NAME
