set verify off
col SCHEDULE_NAME for a30
col OWNER for a20
col JOB_NAME for a30
col PROGRAM for a35
col JOB_TYPE for a18 justify right
col STATE for a15 justify right
col JOB_ACTION for a100 wrapped
col START_DATE for a32
col END_DATE for a32
col LAST_START_DATE for a32
col LAST_RUN_DURATION for a32
col NEXT_RUN_DATE  for a32
col REPEAT_INTERVAL for a71
col SOURCE for a30
col COMMENTS for a100
col JOB_CLASS for a20

accept RUNNING number DEFAULT '0' PROMPT 'RUNNING ONLY?(0 ou 1): '
accept SCHEDULED number default '0' PROMPT 'SCHEDULED ONLY?(0 ou 1): '
accept JOB_NAME CHAR default '%' PROMPT 'LIKE JOB_NAME(DEF %): '
accept JOB_ACTION CHAR default '%' PROMPT 'LIKE JOB_ACTION(DEF %): '

BREAK ON JOB_NAME SKIP 1

SELECT 
	 OWNER
	,JOB_NAME
	,START_DATE
	,END_DATE
	,LAST_START_DATE
	,LAST_RUN_DURATION
	,ENABLED
	,AUTO_DROP
	,MAX_FAILURES
	,RETRY_COUNT
	,LOGGING_LEVEL
	,REPEAT_INTERVAL
	,NEXT_RUN_DATE
FROM DBA_SCHEDULER_JOBS
WHERE (STATE = 'RUNNING' OR &RUNNING=0) 
AND (STATE = 'SCHEDULED' OR &SCHEDULED=0)
AND UPPER(JOB_NAME) LIKE UPPER('&JOB_NAME')
AND UPPER(JOB_ACTION) LIKE UPPER('&JOB_ACTION');


SELECT 
	 OWNER
	,JOB_NAME
	,PROGRAM_OWNER || '-' || PROGRAM_NAME as PROGRAM
	,JOB_TYPE
	,STATE
	,RUN_COUNT
	,FAILURE_COUNT
	,INSTANCE_ID
	,JOB_ACTION
	,SCHEDULE_NAME
	,JOB_CLASS
	,COMMENTS
FROM DBA_SCHEDULER_JOBS
WHERE (STATE = 'RUNNING' OR &RUNNING=0)
AND (STATE = 'SCHEDULED' OR &SCHEDULED=0)
AND UPPER(JOB_NAME) LIKE upper('&JOB_NAME')
AND UPPER(JOB_ACTION) LIKE upper('&JOB_ACTION');

undef RUNNING
undef SCHEDULED
undef JOB_NAME
undef JOB_ACTION
set verify on