column "SESSION_USER" format a15
column "CURRENT_SCHEMA" format a15
column "HOST" format a15
column "INSTANCE" format a5
column "DB_NAME" format a15
column "IP_ADDRESS" format a12
column "AUTHENTICATION_METHOD" format a10
column "LANGUAGE" format a10
column "NLS_DATE_FORMAT" format a10
column "SERVICE_NAME" format a10
column "CLIENT_IDENTIFIER" format a10
column "CURRENT_SQL" format a40 wrapped
column SID for 999999999
col CONTAINER for a10
SELECT to_number(SYS_CONTEXT('USERENV','SID')) SID,
 SYS_CONTEXT('USERENV','SESSION_USER') "SESSION_USER",
 SYS_CONTEXT('USERENV','CURRENT_SCHEMA') "CURRENT_SCHEMA",
 SYS_CONTEXT('USERENV','HOST') "HOST",
 SYS_CONTEXT('USERENV','INSTANCE') "INSTANCE",
 SYS_CONTEXT('USERENV','DB_NAME') "DB_NAME",
 SYS_CONTEXT('USERENV','IP_ADDRESS') "IP_ADDRESS",
 SYS_CONTEXT('USERENV','AUTHENTICATION_METHOD') "AUTHENTICATION_METHOD",
 SYS_CONTEXT('USERENV','LANGUAGE') "LANGUAGE",
 SYS_CONTEXT('USERENV','NLS_DATE_FORMAT') "NLS_DATE_FORMAT",
 SYS_CONTEXT('USERENV','SERVICE_NAME') "SERVICE_NAME",
 SYS_CONTEXT('USERENV','CLIENT_IDENTIFIER') "CLIENT_IDENTIFIER",
 SYS_CONTEXT ('USERENV', 'CON_NAME') CONTAINER,
 SYS_CONTEXT('USERENV','CURRENT_SQL') "CURRENT_SQL"
FROM DUAL;

prompt *** ROLES ATIVAS
select * from session_roles;

select con_id, name, open_mode from v$pdbs;