prompt advisor 
prompt listar objetos candidatos a serem pinados no cache
prompt para pinar usar "EXECUTE DBMS_SHARED_POOL.KEEP(OWNER.TRIGGER, 'R')"
prompt 

prompt DROP TABLE LRU_TMP;
prompt select * from LRU_TMP;

CREATE TABLE LRU_TMP AS SELECT * FROM X$KSMLRU;
INSERT INTO LRU_TMP SELECT * FROM X$KSMLRU;

COL STORED_OBJECT FORMAT A40;
COL SQ_EXECUTIONS FORMAT 999,999;

SELECT /*+ ORDERED USE_HASH(D) USE_HASH(C) */
	O.KGLNAOWN||'.'||O.KGLNAOBJ STORED_OBJECT,
	SUM(C.KGLHDEXC) SQL_EXECUTIONS
FROM SYS.X$KGLOB O, SYS.X$KGLRD D, SYS.X$KGLCURSOR C
WHERE
	O.INST_ID = USERENV('INSTANCE') AND
	D.INST_ID = USERENV('INSTANCE') AND
	C.INST_ID = USERENV('INSTANCE') AND
	O.KGLOBTYP IN (7, 8, 9, 11, 12) AND
	D.KGLHDCDR = O.KGLHDADR AND
	C.KGLHDPAR = D.KGLRDHDL
GROUP BY O.KGLNAOWN, O.KGLNAOBJ
HAVING SUM(C.KGLHDEXC) > 0
ORDER BY 2 DESC;