column PROPERTY_VALUE format a40
column PROPERTY_NAME format a40

SELECT property_name, PROPERTY_VALUE from DATABASE_PROPERTIES where property_name in ('DEFAULT_TEMP_TABLESPACE', 'DEFAULT_USER_TABLESPACE', 'DBTIMEZONE', 'NLS_CHARACTERSET', 'NLS_NCHAR_CHARACTERSET');
