set verify off
set echo off
set long 999999
col SERVICE format a10
col MODULE format a10
col FIRST_LOAD_TIME format a20
col LAST_LOAD_TIME format a20
col force_matching_signature for 999999999999999999999999
define force_matching_signature=&force_matching_signature

prompt "VALOR ACUMULADO:"
	SELECT Sum((SHARABLE_MEM + PERSISTENT_MEM + RUNTIME_MEM)) AS SUM_MEM, 
		   SUM(EXECUTIONS) EXECUTIONS, 
		   SUM(BUFFER_GETS) BUFFER_GETS, 
		   ROUND(SUM(CPU_TIME / 1000)) CPU_TIME_MS, 
		   ROUND(SUM(ELAPSED_TIME / 1000)) ELAPSED_TIME_MS, 
		   SUM(DISK_READS) DISK_READS, 
		   SUM(ROWS_PROCESSED) ROWS_PROCESSED, 
		   SUM(DIRECT_WRITES) DIRECT_WRITES, 
		   SUM(FETCHES) FETCHES, 
		   SUM(USERS_EXECUTING) USERS_EXECUTING
	FROM V$SQL
	WHERE force_matching_signature='&force_matching_signature';
	
prompt 
	SELECT ROUND(SUM(APPLICATION_WAIT_TIME / 1000)) AS APPLICATION_WAIT_MS, 
		ROUND(SUM(CONCURRENCY_WAIT_TIME / 1000)) AS  CONCURRENCY_WAIT_MS,
		ROUND(SUM(CLUSTER_WAIT_TIME / 1000)) AS CLUSTER_WAIT_MS,
		ROUND(SUM(USER_IO_WAIT_TIME / 1000)) AS USER_IO_WAIT_MS,
		ROUND(SUM(PLSQL_EXEC_TIME / 1000)) AS PLSQL_EXEC_MS,
		ROUND(SUM(JAVA_EXEC_TIME / 1000)) AS JAVA_EXEC_MS,
		OPTIMIZER_MODE
	FROM V$SQL
	WHERE force_matching_signature='&force_matching_signature'
	GROUP BY OPTIMIZER_MODE;
	
prompt 
prompt 
prompt "VALOR POR EXECUCAO:"
	SELECT 
		ROUND(SUM((SHARABLE_MEM + PERSISTENT_MEM + RUNTIME_MEM) / DECODE(EXECUTIONS, 0, 1, EXECUTIONS))) AS SUM_MEM, 
		ROUND(SUM(BUFFER_GETS / DECODE(EXECUTIONS, 0, 1, EXECUTIONS))) AS AVG_BUFFER_GETS, 
		ROUND(SUM((CPU_TIME  / DECODE(EXECUTIONS, 0, 1, EXECUTIONS))/ 1000))  AS AVG_CPU_MS,
		ROUND(SUM((ELAPSED_TIME / DECODE(EXECUTIONS, 0, 1, EXECUTIONS)) / 1000))   AS AVG_ELAPSED_MS,
		ROUND(SUM(DISK_READS  / DECODE(EXECUTIONS, 0, 1, EXECUTIONS))) AS AVG_DISK_READS,
		ROUND(SUM(ROWS_PROCESSED / DECODE(EXECUTIONS, 0, 1, EXECUTIONS))) AS AVG_ROWS,
		ROUND(SUM(DIRECT_WRITES / DECODE(EXECUTIONS, 0, 1, EXECUTIONS))) AS AVG_DIRECT_WRITES,
		ROUND(SUM(FETCHES / DECODE(EXECUTIONS, 0, 1, EXECUTIONS))) AS AVG_FETCHES
	FROM V$SQL
	WHERE force_matching_signature='&force_matching_signature';
	
prompt "WAIT TIME POR EXECUCAO EM MILISEGUNDOS"
	SELECT 
		ROUND(SUM((APPLICATION_WAIT_TIME/ DECODE(EXECUTIONS, 0, 1, EXECUTIONS)) /1000)) AS AVG_APPLICATION_TIME, 
		ROUND(SUM((CONCURRENCY_WAIT_TIME/ DECODE(EXECUTIONS, 0, 1, EXECUTIONS)) /1000)) AS AVG_CONCURRENCY_TIME, 
		ROUND(SUM((USER_IO_WAIT_TIME/ DECODE(EXECUTIONS, 0, 1, EXECUTIONS)) /1000)) AS AVG_IO_TIME, 
		ROUND(SUM((PLSQL_EXEC_TIME/ DECODE(EXECUTIONS, 0, 1, EXECUTIONS)) /1000)) AS AVG_PLSQL_TIME, 
		ROUND(SUM((JAVA_EXEC_TIME/ DECODE(EXECUTIONS, 0, 1, EXECUTIONS)) /1000)) AS AVG_JAVA_TIME,
		ROUND(SUM((CLUSTER_WAIT_TIME/ DECODE(EXECUTIONS, 0, 1, EXECUTIONS)) /1000)) AS AVG_CLUSTER_TIME 
	FROM V$SQL
	WHERE force_matching_signature='&force_matching_signature';
	
prompt 
prompt "GERAL DO SQL:"                         
	SELECT PLAN_HASH_VALUE, sql_id, child_number, HASH_VALUE, SERVICE, MODULE, FIRST_LOAD_TIME, LAST_LOAD_TIME, PROGRAM_ID, PROGRAM_LINE#, USERS_EXECUTING, OPTIMIZER_MODE, PARSING_SCHEMA_NAME
	FROM V$SQL
	WHERE force_matching_signature='&force_matching_signature'
	order by PLAN_HASH_VALUE;
prompt 
prompt 

col sql_text format a999
SELECT
         T.SQL_TEXT
FROM     V$SQLTEXT T,
		 (select sql_id from v$sql where force_matching_signature = '&force_matching_signature' and rownum = 1) tbl
WHERE    T.SQL_ID =tbl.sql_id
ORDER BY T.PIECE;

UNDEF force_matching_signature
set verify on