set verify off
set echo off
set long 999999
col SERVICE format a10
col MODULE format a10
col FIRST_LOAD_TIME format a20
col LAST_LOAD_TIME format a20
define sql_id=&sql_id
prompt "VALOR ACUMULADO:"
	SELECT child_number, (SHARABLE_MEM + PERSISTENT_MEM + RUNTIME_MEM) AS SUM_MEM, EXECUTIONS, BUFFER_GETS, 
		ROUND(CPU_TIME / 1000) CPU_MS,  
		ROUND(ELAPSED_TIME / 1000) ELAPSED_MS, 
		DISK_READS, ROWS_PROCESSED, DIRECT_WRITES, FETCHES, USERS_EXECUTING
	FROM V$SQL
	WHERE SQL_ID='&sql_id';
prompt 
	SELECT child_number, 
			ROUND(APPLICATION_WAIT_TIME / 1000) APPLICATION_WAIT_MS, 
			ROUND(CONCURRENCY_WAIT_TIME / 1000) CONCURRENCY_WAIT_MS, 
			ROUND(CLUSTER_WAIT_TIME / 1000) CLUSTER_WAIT_MS, 
			ROUND(USER_IO_WAIT_TIME / 1000) USER_IO_WAIT_MS, 
			ROUND(PLSQL_EXEC_TIME / 1000) PLSQL_EXEC_MS, 
			ROUND(JAVA_EXEC_TIME / 1000) JAVA_EXEC_MS, 
			OPTIMIZER_MODE
	FROM V$SQL
	WHERE SQL_ID='&sql_id';
prompt 
prompt 
prompt "VALOR POR EXECUCAO:"
	SELECT child_number, round((SHARABLE_MEM + PERSISTENT_MEM + RUNTIME_MEM) / DECODE(EXECUTIONS, 0, 1, EXECUTIONS)) AS SUM_MEM, 
		   ROUND(BUFFER_GETS / DECODE(EXECUTIONS, 0, 1, EXECUTIONS)) AS AVG_BUFFER_GETS, 
		ROUND((CPU_TIME  / DECODE(EXECUTIONS, 0, 1, EXECUTIONS))/ 1000)  AS AVG_CPU_MS,
		ROUND((ELAPSED_TIME / DECODE(EXECUTIONS, 0, 1, EXECUTIONS)) / 1000)   AS AVG_ELAPSED_MS,
		ROUND(DISK_READS  / DECODE(EXECUTIONS, 0, 1, EXECUTIONS)) AS AVG_DISK_READS,
		ROUND(ROWS_PROCESSED / DECODE(EXECUTIONS, 0, 1, EXECUTIONS)) AS AVG_ROWS,
		ROUND(DIRECT_WRITES / DECODE(EXECUTIONS, 0, 1, EXECUTIONS)) AS AVG_DIRECT_WRITES,
		ROUND(FETCHES / DECODE(EXECUTIONS, 0, 1, EXECUTIONS)) AS AVG_FETCHES
	FROM V$SQL
	WHERE SQL_ID='&sql_id';
prompt "WAIT TIME POR EXECUCAO EM MILISEGUNDOS"
	SELECT child_number, 
		ROUND((APPLICATION_WAIT_TIME/ DECODE(EXECUTIONS, 0, 1, EXECUTIONS)) /1000) AS AVG_APPLICATION_TIME, 
		ROUND((CONCURRENCY_WAIT_TIME/ DECODE(EXECUTIONS, 0, 1, EXECUTIONS)) /1000) AS AVG_CONCURRENCY_TIME, 
		ROUND((USER_IO_WAIT_TIME/ DECODE(EXECUTIONS, 0, 1, EXECUTIONS)) /1000) AS AVG_IO_TIME, 
		ROUND((PLSQL_EXEC_TIME/ DECODE(EXECUTIONS, 0, 1, EXECUTIONS)) /1000) AS AVG_PLSQL_TIME, 
		ROUND((JAVA_EXEC_TIME/ DECODE(EXECUTIONS, 0, 1, EXECUTIONS)) /1000) AS AVG_JAVA_TIME,
		ROUND((CLUSTER_WAIT_TIME/ DECODE(EXECUTIONS, 0, 1, EXECUTIONS)) /1000) AS AVG_CLUSTER_TIME 
	FROM V$SQL
	WHERE SQL_ID='&sql_id';
prompt 
prompt "GERAL DO SQL:"                         
	SELECT child_number, HASH_VALUE, SERVICE, MODULE, FIRST_LOAD_TIME, LAST_LOAD_TIME, PROGRAM_ID, PROGRAM_LINE#, USERS_EXECUTING, OPTIMIZER_MODE, PARSING_SCHEMA_NAME, PLAN_HASH_VALUE
	FROM V$SQL
	WHERE SQL_ID='&sql_id';
prompt 
prompt 
col sql_text format a999
SELECT
         T.SQL_TEXT
FROM     V$SQLTEXT T
WHERE    T.SQL_ID ='&sql_id'
ORDER BY T.PIECE;
UNDEF sql_id
set verify on