set verify off
set echo off
set long 999999
define sql_id=&sql_id
prompt "VALOR ACUMULADO:"
	SELECT (SHARABLE_MEM + PERSISTENT_MEM + RUNTIME_MEM) AS SUM_MEM, EXECUTIONS, BUFFER_GETS, CPU_TIME, ELAPSED_TIME, DISK_READS, ROWS_PROCESSED, DIRECT_WRITES, FETCHES, USERS_EXECUTING
	FROM V$SQL
	WHERE SQL_ID='&sql_id';
prompt 
	SELECT APPLICATION_WAIT_TIME, CONCURRENCY_WAIT_TIME, CLUSTER_WAIT_TIME, USER_IO_WAIT_TIME, PLSQL_EXEC_TIME, JAVA_EXEC_TIME, OPTIMIZER_MODE
	FROM V$SQL
	WHERE SQL_ID='&sql_id';
prompt 
prompt 
prompt "VALOR POR EXECUCAO:"
	SELECT round((SHARABLE_MEM + PERSISTENT_MEM + RUNTIME_MEM) / DECODE(EXECUTIONS, 0, 1, EXECUTIONS)) AS SUM_MEM, 
		   ROUND(BUFFER_GETS / DECODE(EXECUTIONS, 0, 1, EXECUTIONS)) AS AVG_BUFFER_GETS, 
		ROUND((CPU_TIME  / DECODE(EXECUTIONS, 0, 1, EXECUTIONS))/ 1000)  AS AVG_CPU_MS,
		ROUND((ELAPSED_TIME / DECODE(EXECUTIONS, 0, 1, EXECUTIONS)) / 1000)   AS AVG_ELAPSED_MS,
		ROUND(DISK_READS  / DECODE(EXECUTIONS, 0, 1, EXECUTIONS)) AS AVG_DISK_READS,
		ROUND(ROWS_PROCESSED / DECODE(EXECUTIONS, 0, 1, EXECUTIONS)) AS AVG_ROWS,
		ROUND(DIRECT_WRITES / DECODE(EXECUTIONS, 0, 1, EXECUTIONS)) AS AVG_DIRECT_WRITES,
		ROUND(FETCHES / DECODE(EXECUTIONS, 0, 1, EXECUTIONS)) AS AVG_FETCHES
	FROM V$SQL
	WHERE SQL_ID='&sql_id';
prompt 
	SELECT ROUND(APPLICATION_WAIT_TIME/ DECODE(EXECUTIONS, 0, 1, EXECUTIONS)) AS AVG_APPLICATION_TIME, 
		ROUND(CONCURRENCY_WAIT_TIME/ DECODE(EXECUTIONS, 0, 1, EXECUTIONS)) AS AVG_CONCURRENCY_TIME, 
		ROUND(USER_IO_WAIT_TIME/ DECODE(EXECUTIONS, 0, 1, EXECUTIONS)) AS AVG_IO_TIME, 
		ROUND(PLSQL_EXEC_TIME/ DECODE(EXECUTIONS, 0, 1, EXECUTIONS)) AS AVG_PLSQL_TIME, 
		ROUND(JAVA_EXEC_TIME/ DECODE(EXECUTIONS, 0, 1, EXECUTIONS)) AS AVG_JAVA_TIME,
		ROUND(CLUSTER_WAIT_TIME/ DECODE(EXECUTIONS, 0, 1, EXECUTIONS)) AS AVG_CLUSTER_TIME 
	FROM V$SQL
	WHERE SQL_ID='&sql_id';
prompt 
prompt "GERAL DO SQL:"                         
	SELECT HASH_VALUE, SERVICE, MODULE, FIRST_LOAD_TIME, LAST_LOAD_TIME, PROGRAM_ID, PROGRAM_LINE#, USERS_EXECUTING, OPTIMIZER_MODE, IS_BIND_SENSITIVE, IS_BIND_AWARE
	FROM V$SQL
	WHERE SQL_ID='&sql_id';
prompt 
prompt "Statisticas por conjunto de BIND Adpatative Cursor Sharing"
SELECT * 
FROM v$sql_cs_statistics 
WHERE sql_id = '&sql_id';
prompt 
col sql_text format a999
SELECT
         T.SQL_TEXT
FROM     V$SQLTEXT T
WHERE    T.SQL_ID ='&sql_id'
ORDER BY T.PIECE;
UNDEFINE sql_id