Accept dt1  prompt 'Begin (dd/mm/yyyy hh24:mi:ss):'
Accept dt2  prompt 'End   (dd/mm/yyyy hh24:mi:ss):'
define UNDOTS_id = &UNDOTS_id
define INSTANCE_NUMBER = &INSTANCE_NUMBER

SELECT SNAP_ID, 
	INSTANCE_NUMBER,
	TO_CHAR(BEGIN_TIME, 'DD/MM/YYYY HH24:MI:SS') BEGIN_TIME,
         TO_CHAR(END_TIME, 'DD/MM/YYYY HH24:MI:SS') END_TIME,
         UNDOTSN UNDOTS_ID, UNDOBLKS, TXNCOUNT TRANS_CTD, MAXCONCURRENCY AS "MAXCON", 
	 MAXQUERYLEN LONGEST_QUERY_SEC, 
	 MAXQUERYSQLID LONGEST_SQL_ID,
	 SSOLDERRCNT CTD_SOLD_ERR,
	 NOSPACEERRCNT CTD_NOSPACE_ERR
  FROM DBA_HIST_UNDOSTAT 
  WHERE BEGIN_TIME between TO_DATE('&dt1', 'dd/mm/yyyy hh24:mi:ss') and TO_DATE('&dt2', 'dd/mm/yyyy hh24:mi:ss')
  and (UNDOTSN = &UNDOTS_id or &UNDOTS_id = 0)
  and (INSTANCE_NUMBER = &INSTANCE_NUMBER or &INSTANCE_NUMBER =0)
  ORDER BY BEGIN_TIME;

undef dt1
undef dt2
undef INSTANCE_NUMBER
undef UNDOTS_id