SELECT *
FROM 
(  SELECT TO_CHAR(BEGIN_TIME, 'MM/DD/YYYY HH24:MI:SS') BEGIN_TIME,
         TO_CHAR(END_TIME, 'MM/DD/YYYY HH24:MI:SS') END_TIME,
         UNDOTSN UNDOTS_ID, UNDOBLKS, TXNCOUNT TRANS_CTD, MAXCONCURRENCY AS "MAXCON", 
	 MAXQUERYLEN LONGEST_QUERY_SEC, 
	 MAXQUERYID LONGEST_SQL_ID,
	 SSOLDERRCNT CTD_SOLD_ERR,
	 NOSPACEERRCNT CTD_NOSPACE_ERR
  FROM v$UNDOSTAT 
  ORDER BY BEGIN_TIME desc)
WHERE ROWNUM < 150
ORDER BY BEGIN_TIME;