17:05:26 orahlg01>
17:05:29 orahlg01>select count(1) as ctd, owner from dba_objects where lower(owner) in  ('infra_bridge7br',
17:05:29   2  'infra_celular',
17:05:29   3  'infra_mail',
17:05:29   4  'infra_newsletter',
17:05:29   5  'infra_sagu',
17:05:29   6  'infra_saiter',
17:05:29   7  'infrahlg_suat',
17:05:29   8  'trrmd3',
17:05:29   9  'voip')
17:05:29  10  group by owner
17:05:29  11  order by 1;

       CTD OWNER                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
---------- ------------------------------                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
        22 VOIP                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
        41 INFRA_CELULAR                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
        47 INFRA_NEWSLETTER                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
        55 INFRA_MAIL                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
        67 INFRA_SAGU                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
        73 INFRA_SAITER                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
       142 TRRMD3                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
       149 INFRA_BRIDGE7BR                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
      1830 INFRAHLG_SUAT                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                

9 linhas selecionadas.

17:05:31 orahlg01>
17:05:40 orahlg01>SELECT object_name, object_type, COUNT(1)
17:05:40   2  FROM (
17:05:40   3  select object_name, owner, object_type
17:05:40   4  from dba_objects o
17:05:40   5  where exists (
17:05:40   6  select 1
17:05:40   7  from dba_objects oo
17:05:40   8  where lower(oo.owner) in  ('infra_bridge7br',
17:05:41   9  'infra_celular',
17:05:41  10  'infra_mail',
17:05:41  11  'infra_newsletter',
17:05:41  12  'infra_sagu',
17:05:41  13  'infra_saiter',
17:05:41  14  'infrahlg_suat',
17:05:41  15  'trrmd3',
17:05:41  16  'voip'
17:05:41  17  )
17:05:41  18  and oo.owner <> o.owner
17:05:41  19  and oo.object_name = o.object_name
17:05:41  20  )
17:05:41  21  and lower(o.owner) in  ('infra_bridge7br',
17:05:41  22  'infra_celular',
17:05:41  23  'infra_mail',
17:05:41  24  'infra_newsletter',
17:05:41  25  'infra_sagu',
17:05:41  26  'infra_saiter',
17:05:41  27  'infrahlg_suat',
17:05:41  28  'trrmd3',
17:05:41  29  'voip'
17:05:41  30  )) TBL
17:05:41  31  where object_type not in ('INDEX', 'SEQUENCE')
17:05:41  32  GROUP BY object_name, object_type
17:05:41  33  having count(1) > 1
17:05:41  34  order by 1;

OBJECT_NAME                                                                                                                      OBJECT_TYPE           COUNT(1)                                                                                                                                                                                                                                                                                                                                                                                                                                                         
-------------------------------------------------------------------------------------------------------------------------------- ------------------- ----------                                                                                                                                                                                                                                                                                                                                                                                                                                                         
CG_REF_CODES                                                                                                                     TABLE                        2                                                                                                                                                                                                                                                                                                                                                                                                                                                         
PLAN_TABLE                                                                                                                       TABLE                        3                                                                                                                                                                                                                                                                                                                                                                                                                                                         
SQUIRREL_GET_ERROR_OFFSET                                                                                                        FUNCTION                     3                                                                                                                                                                                                                                                                                                                                                                                                                                                         
TRR_ALIAS                                                                                                                        SYNONYM                      2                                                                                                                                                                                                                                                                                                                                                                                                                                                         
TRR_ATRIBUTO                                                                                                                     TABLE                        2                                                                                                                                                                                                                                                                                                                                                                                                                                                         
TRR_COD_DOMINIOS                                                                                                                 SYNONYM                      2                                                                                                                                                                                                                                                                                                                                                                                                                                                         
TRR_CONTA                                                                                                                        SYNONYM                      2                                                                                                                                                                                                                                                                                                                                                                                                                                                         
TRR_DOMINIO                                                                                                                      TABLE                        2                                                                                                                                                                                                                                                                                                                                                                                                                                                         
TRR_EQUIPE                                                                                                                       TABLE                        3                                                                                                                                                                                                                                                                                                                                                                                                                                                         
TRR_EQUIPE_SERVICOINT                                                                                                            TABLE                        2                                                                                                                                                                                                                                                                                                                                                                                                                                                         
TRR_EQUIPE_USUARIO                                                                                                               TABLE                        2                                                                                                                                                                                                                                                                                                                                                                                                                                                         
TRR_FNC_CLEANER_GET_USERS                                                                                                        FUNCTION                     2                                                                                                                                                                                                                                                                                                                                                                                                                                                         
TRR_FNC_USERDEL                                                                                                                  FUNCTION                     2                                                                                                                                                                                                                                                                                                                                                                                                                                                         
TRR_FNC_USERINC                                                                                                                  FUNCTION                     2                                                                                                                                                                                                                                                                                                                                                                                                                                                         
TRR_FNC_UTL_LOWERCASE                                                                                                            FUNCTION                     2                                                                                                                                                                                                                                                                                                                                                                                                                                                         
TRR_GRUPO_NAMESPACE                                                                                                              TABLE                        2                                                                                                                                                                                                                                                                                                                                                                                                                                                         
TRR_LOG                                                                                                                          TABLE                        2                                                                                                                                                                                                                                                                                                                                                                                                                                                         
TRR_MOTIVO_STATUS                                                                                                                SYNONYM                      2                                                                                                                                                                                                                                                                                                                                                                                                                                                         
TRR_NAMESPACE                                                                                                                    TABLE                        2                                                                                                                                                                                                                                                                                                                                                                                                                                                         
TRR_OPERACAO                                                                                                                     TABLE                        2                                                                                                                                                                                                                                                                                                                                                                                                                                                         
TRR_PCK_CUR_TYPE                                                                                                                 PACKAGE                      4                                                                                                                                                                                                                                                                                                                                                                                                                                                         
TRR_PERFIL_SERVICO                                                                                                               TABLE                        2                                                                                                                                                                                                                                                                                                                                                                                                                                                         
TRR_REGISTRO_SERVICOCONTA                                                                                                        SYNONYM                      2                                                                                                                                                                                                                                                                                                                                                                                                                                                         
TRR_SENHAS                                                                                                                       SYNONYM                      2                                                                                                                                                                                                                                                                                                                                                                                                                                                         
TRR_SERVICO                                                                                                                      TABLE                        2                                                                                                                                                                                                                                                                                                                                                                                                                                                         
TRR_SERVICO_INTERNO                                                                                                              TABLE                        2                                                                                                                                                                                                                                                                                                                                                                                                                                                         
TRR_SERVICOINT_USUARIO                                                                                                           TABLE                        2                                                                                                                                                                                                                                                                                                                                                                                                                                                         
TRR_STATUS                                                                                                                       SYNONYM                      2                                                                                                                                                                                                                                                                                                                                                                                                                                                         
TRR_SUBMOTIVO_STATUS                                                                                                             SYNONYM                      2                                                                                                                                                                                                                                                                                                                                                                                                                                                         
TRR_USR_ASSINANTES                                                                                                               SYNONYM                      2                                                                                                                                                                                                                                                                                                                                                                                                                                                         
TRR_USUARIO                                                                                                                      TABLE                        2                                                                                                                                                                                                                                                                                                                                                                                                                                                         
TRR_USUARIO                                                                                                                      SYNONYM                      2                                                                                                                                                                                                                                                                                                                                                                                                                                                         

32 linhas selecionadas.

17:05:42 orahlg01>spool off
