define dir_scripts=&1
define dir_data=&2

connect SYS/change_on_install as SYSDBA
set echo on
spool &dir_scripts/CreateDBFiles.log
CREATE TABLESPACE "DRSYS" 	LOGGING DATAFILE '&dir_data/drsys01.dbf' 	SIZE 20M AUTOEXTEND ON NEXT 10m MAXSIZE 2000m EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT  AUTO ;
CREATE TABLESPACE "INDX" 	LOGGING DATAFILE '&dir_data/indx01.dbf' 	SIZE 25M AUTOEXTEND ON NEXT 10m MAXSIZE 2000m EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT  AUTO ;
CREATE TABLESPACE "TOOLS" 	LOGGING DATAFILE '&dir_data/tools01.dbf' 	SIZE 10M AUTOEXTEND ON NEXT 10m MAXSIZE 2000m EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT  AUTO ;
CREATE TABLESPACE "USERS" 	LOGGING DATAFILE '&dir_data/users01.dbf' 	SIZE 25M AUTOEXTEND ON NEXT 10m MAXSIZE 2000m EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT  AUTO ;
CREATE TABLESPACE "XDB" 	LOGGING DATAFILE '&dir_data/xdb01.dbf' 		SIZE 20M AUTOEXTEND ON NEXT 10m MAXSIZE 2000m EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT  AUTO ;
spool off
exit;
